<?php
/**
 * @category	Neteven
 * @package		Neteven_NetevenSync
 * @copyright	Copyright (c) 2013 Agence Soon. (http://www.agence-soon.fr)
 * @licence		http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author		Hervé G. - Twitter : @vrnet
 */ 
?>
<?php
$button = $this->getLayout()->createBlock('adminhtml/widget_button')
	->setData(array(
			'label'     => Mage::helper('netevensync')->__('Remove Selected Products from Selection'),
			'onclick'   => 'submitProductSelectionForm(\'' . $this->getUrl('*/*/removeProducts') . '\')',
			'class'   	=> 'delete',
			'id'		=> 'removed_products_button'
	));
?>
<h3><?php echo $this->__('Exported Products')?></h3>
<p class="switcher a-right">
	<?php echo $button->toHtml(); ?>
</p>
<div class="divider"></div>