<?php
/**
 * Notifications template
 *
 * @category	Neteven
 * @package		Neteven_NetevenSync
 * @copyright	Copyright (c) 2013 Agence Soon. (http://www.agence-soon.fr)
 * @licence		http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author		Hervé G. - Twitter : @vrnet
 */ 
?>
<?php $errors = $this->getErrors()?>
<?php if(count($errors) > 0) :?>
	<div class="notification-global">
		<strong><?php echo $this->helper('netevensync')->__('One or more errors occured during the following Neteven synchronization processes:')?></strong>
		<?php echo strtolower(implode(', ', $errors)); ?>.
		<?php echo $this->helper('netevensync')->__('Please see log file var/log/neteven.log for details. <a href="%s">Delete</a>', $this->getCleanUrl())?>
	</div>
<?php endif; ?>