<?php
/**
 * Hint for shipping system configuration
 *
 * @license http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author Hervé Guétin <@herveguetin> <herve.guetin@agence-soon.fr>
 * @category Neteven
 * @package Neteven_NetevenSync
 * @copyright Copyright (c) 2013 Agence Soon (http://www.agence-soon.fr)
 */
?>
<div class="notification-global" style="margin-bottom: 20px; border: 1px solid #eee2be;">
    <?php echo $this->getText(); ?>
</div>